# Autogenerated by nbdev

d = { 'settings': {'branch': '', 'doc_baseurl': '/', 'doc_host': 'https://.github.io', 'git_url': 'https://github.com//', 'lib_path': ''},
  'syms': { 'nbdev-demo-230204.core': {'nbdev-demo-230204.core.foo': ('core.html#foo', 'nbdev-demo-230204/core.py')},
            'nbdev-demo-230204.setup': {}}}
